import type { Metadata } from "next";
import { EB_Garamond } from 'next/font/google';
import "./globals.css";

const ebGaramond = EB_Garamond({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ebGaramond.className`}
      >
        {children}
      </body>
    </html>
  );
}
